public class CheckAccess{
    
    public void checkObjectAccess(){
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.isUpdateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.isCreateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.isAccessible());
        
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__Active__c.isUpdateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__Active__c.isCreateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__Active__c.isAccessible());
        
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__Editable__c.isUpdateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__Editable__c.isCreateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__Editable__c.isAccessible());
        
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__EndDate__c.isUpdateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__EndDate__c.isCreateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__EndDate__c.isAccessible());
        
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__FinancialAccount__c.isUpdateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__FinancialAccount__c.isCreateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__FinancialAccount__c.isAccessible());
        
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__RelatedAccount__c.isUpdateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__RelatedAccount__c.isCreateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__RelatedAccount__c.isAccessible());
        
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__RelatedContact__c.isUpdateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__RelatedContact__c.isCreateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__RelatedContact__c.isAccessible());
        
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__Role__c.isUpdateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__Role__c.isCreateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__Role__c.isAccessible());
        
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__SourceSystemId__c.isUpdateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__SourceSystemId__c.isCreateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__SourceSystemId__c.isAccessible());        
        
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__StartDate__c.isUpdateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__StartDate__c.isCreateable());
        System.debug(Schema.sObjectType.FinServ__FinancialAccountRole__c.fields.FinServ__StartDate__c.isAccessible());        
        
        
    }
    
       
}